### ISSUE TITLE
help_document

### ISSUE THREAD

**Issue by qingyang0315** [usman912349/Master_Nicola#1]
Is there any help document?

**Comment by usman912349** [comment]
Thank you very much for your query. This code is originally for the implementation of Discrete Dislocation Plasticity (DDP) theory (E Van der Giessen and A Needleman 1995 Modelling Simul. Mater. Sci. Eng. 3 689). You can find the paper here (https://iopscience.iop.org/article/10.1088/0965-0393/3/5/008/meta). Over the period of time the code was changed for different phenomena, as mentioned in the README file.

The most recent change is the implementation of XFEM in the conventional DDP code to incorporate the non-convex material discontinuities. Please also check the reference: 
"Effect of shape on void growth: A coupled Extended Finite Element Method (XFEM) and Discrete Dislocation Plasticity (DDP) study" https://doi.org/10.1016/j.euromechsol.2021.104471

Please feel free to contact for any furthers queries.
