### ISSUE TITLE
Beginner's Assistance

### ISSUE THREAD

**Issue by Max-useful** [usman912349/Master_Nicola#2]
I am glad to have found your sharing of knowledge on dislocation dynamics, and I was wondering if I could be lucky enough to receive a recent response from you. 

I have recently started exploring the field of dislocation dynamics, and going from zero to one has been a challenging process. Could you please share with me the source code for dislocation dynamics on a two-dimensional plane, if it is convenient for you? My email address is 767737793@qq.com.

 I would greatly appreciate any help that I can gain from it.

**Comment by usman912349** [comment]
Thanks for showing interest in my work. For now, I can recommend some articles.

- The initial 2D planar DDP was developed by Van der Giessen and Alan Needlemen in this article:  "Discrete dislocation plasticity: a simple planar model"
https://iopscience.iop.org/article/10.1088/0965-0393/3/5/008/meta

- This code was used to validate the results which are published in this article: "Effect of shape on void growth: A coupled Extended Finite Element Method (XFEM) and Discrete Dislocation Plasticity (DDP) study"
https://www.sciencedirect.com/science/article/abs/pii/S0997753821002199?via%3Dihub

I hope the above papers will give you a good idea. If you have any further queries, please feel free to contact me.

--
Kind regards
Muhammad Usman

**Comment by usman912349** [comment]
Thanks for showing interest in my work. For now, I can recommend some articles.

- The initial 2D planar DDP was developed by Van der Giessen and Alan Needlemen in this article:  "Discrete dislocation plasticity: a simple planar model"
https://iopscience.iop.org/article/10.1088/0965-0393/3/5/008/meta

- This code was used to validate the results which are published in this article: "Effect of shape on void growth: A coupled Extended Finite Element Method (XFEM) and Discrete Dislocation Plasticity (DDP) study"
https://www.sciencedirect.com/science/article/abs/pii/S0997753821002199?via%3Dihub

I hope the above papers will give you a good idea. If you have any further queries, please feel free to contact me.

--
Kind regards
Muhammad Usman
